# Generated by Django 4.2.4 on 2023-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_descriptions_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
