# Generated by Django 4.2.4 on 2023-09-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
